#############################################################################
# Makefile for building: NefClassPRO.app/Contents/MacOS/NefClassPRO
# Generated by qmake (3.0) (Qt 5.6.2)
# Project:  NefClassMAC.pro
# Template: app
# Command: /Users/igorvarga/anaconda3/bin/qmake -spec macx-xcode -o NefClassPRO.xcodeproj/project.pbxproj NefClassMAC.pro
#############################################################################

MAKEFILE      = project.pbxproj

MOC       = /Users/igorvarga/anaconda3/bin/moc
UIC       = /Users/igorvarga/anaconda3/bin/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH       = -I. -I../anaconda3/include/qt -I../anaconda3/include/qt/QtPrintSupport -I../anaconda3/include/qt/QtWidgets -I../anaconda3/include/qt/QtGui -I../anaconda3/include/qt/QtCore -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../anaconda3/mkspecs/macx-clang
DEL_FILE  = rm -f
MOVE      = mv -f

preprocess: compilers
clean preprocess_clean: compiler_clean

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compilers: moc_mainwindow.cpp moc_qcustomplot.cpp ui_mainwindow.h
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_qcustomplot.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_qcustomplot.cpp
moc_mainwindow.cpp: ../anaconda3/include/qt/QtWidgets/qmainwindow.h \
		fuzzyneuralnetwork.h \
		gauss.h \
		rule.h \
		Gauss.h \
		qcustomplot.h \
		../anaconda3/include/qt/QtCore/qglobal.h \
		../anaconda3/include/qt/QtCore/QObject \
		../anaconda3/include/qt/QtCore/QPointer \
		../anaconda3/include/qt/QtCore/QSharedPointer \
		../anaconda3/include/qt/QtCore/QTimer \
		../anaconda3/include/qt/QtGui/QPainter \
		../anaconda3/include/qt/QtGui/QPaintEvent \
		../anaconda3/include/qt/QtGui/QMouseEvent \
		../anaconda3/include/qt/QtGui/QWheelEvent \
		../anaconda3/include/qt/QtGui/QPixmap \
		../anaconda3/include/qt/QtCore/QVector \
		../anaconda3/include/qt/QtCore/QString \
		../anaconda3/include/qt/QtCore/QDateTime \
		../anaconda3/include/qt/QtCore/QMultiMap \
		../anaconda3/include/qt/QtCore/QFlags \
		../anaconda3/include/qt/QtCore/QDebug \
		../anaconda3/include/qt/QtCore/QStack \
		../anaconda3/include/qt/QtCore/QCache \
		../anaconda3/include/qt/QtCore/QMargins \
		../anaconda3/include/qt/QtCore/qmath.h \
		../anaconda3/include/qt/QtGui/QOpenGLContext \
		../anaconda3/include/qt/QtGui/QOpenGLFramebufferObject \
		../anaconda3/include/qt/QtGui/QOffscreenSurface \
		../anaconda3/include/qt/QtGui/QWindow \
		../anaconda3/include/qt/QtOpenGL/QGLPixelBuffer \
		../anaconda3/include/qt/QtCore/qnumeric.h \
		../anaconda3/include/qt/QtCore/QtNumeric \
		../anaconda3/include/qt/QtWidgets/QWidget \
		../anaconda3/include/qt/QtPrintSupport/QtPrintSupport \
		mainwindow.h
	/Users/igorvarga/anaconda3/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/igorvarga/anaconda3/mkspecs/macx-clang -I/Users/igorvarga/NefClass2 -I/Users/igorvarga/anaconda3/include/qt -I/Users/igorvarga/anaconda3/include/qt/QtPrintSupport -I/Users/igorvarga/anaconda3/include/qt/QtWidgets -I/Users/igorvarga/anaconda3/include/qt/QtGui -I/Users/igorvarga/anaconda3/include/qt/QtCore -I/Volumes/100GB/conda/conda-bld/qt_1506025760946/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/c++/v1 -I/Volumes/100GB/conda/conda-bld/qt_1506025760946/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/clang/4.0.1/include -I/opt/MacOSX10.9.sdk/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_qcustomplot.cpp: ../anaconda3/include/qt/QtCore/qglobal.h \
		../anaconda3/include/qt/QtCore/QObject \
		../anaconda3/include/qt/QtCore/QPointer \
		../anaconda3/include/qt/QtCore/QSharedPointer \
		../anaconda3/include/qt/QtCore/QTimer \
		../anaconda3/include/qt/QtGui/QPainter \
		../anaconda3/include/qt/QtGui/QPaintEvent \
		../anaconda3/include/qt/QtGui/QMouseEvent \
		../anaconda3/include/qt/QtGui/QWheelEvent \
		../anaconda3/include/qt/QtGui/QPixmap \
		../anaconda3/include/qt/QtCore/QVector \
		../anaconda3/include/qt/QtCore/QString \
		../anaconda3/include/qt/QtCore/QDateTime \
		../anaconda3/include/qt/QtCore/QMultiMap \
		../anaconda3/include/qt/QtCore/QFlags \
		../anaconda3/include/qt/QtCore/QDebug \
		../anaconda3/include/qt/QtCore/QStack \
		../anaconda3/include/qt/QtCore/QCache \
		../anaconda3/include/qt/QtCore/QMargins \
		../anaconda3/include/qt/QtCore/qmath.h \
		../anaconda3/include/qt/QtGui/QOpenGLContext \
		../anaconda3/include/qt/QtGui/QOpenGLFramebufferObject \
		../anaconda3/include/qt/QtGui/QOffscreenSurface \
		../anaconda3/include/qt/QtGui/QWindow \
		../anaconda3/include/qt/QtOpenGL/QGLPixelBuffer \
		../anaconda3/include/qt/QtCore/qnumeric.h \
		../anaconda3/include/qt/QtCore/QtNumeric \
		../anaconda3/include/qt/QtWidgets/QWidget \
		../anaconda3/include/qt/QtPrintSupport/QtPrintSupport \
		qcustomplot.h
	/Users/igorvarga/anaconda3/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/igorvarga/anaconda3/mkspecs/macx-clang -I/Users/igorvarga/NefClass2 -I/Users/igorvarga/anaconda3/include/qt -I/Users/igorvarga/anaconda3/include/qt/QtPrintSupport -I/Users/igorvarga/anaconda3/include/qt/QtWidgets -I/Users/igorvarga/anaconda3/include/qt/QtGui -I/Users/igorvarga/anaconda3/include/qt/QtCore -I/Volumes/100GB/conda/conda-bld/qt_1506025760946/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/c++/v1 -I/Volumes/100GB/conda/conda-bld/qt_1506025760946/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/clang/4.0.1/include -I/opt/MacOSX10.9.sdk/usr/include qcustomplot.h -o moc_qcustomplot.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		qcustomplot.h \
		../anaconda3/include/qt/QtCore/qglobal.h \
		../anaconda3/include/qt/QtCore/QObject \
		../anaconda3/include/qt/QtCore/QPointer \
		../anaconda3/include/qt/QtCore/QSharedPointer \
		../anaconda3/include/qt/QtCore/QTimer \
		../anaconda3/include/qt/QtGui/QPainter \
		../anaconda3/include/qt/QtGui/QPaintEvent \
		../anaconda3/include/qt/QtGui/QMouseEvent \
		../anaconda3/include/qt/QtGui/QWheelEvent \
		../anaconda3/include/qt/QtGui/QPixmap \
		../anaconda3/include/qt/QtCore/QVector \
		../anaconda3/include/qt/QtCore/QString \
		../anaconda3/include/qt/QtCore/QDateTime \
		../anaconda3/include/qt/QtCore/QMultiMap \
		../anaconda3/include/qt/QtCore/QFlags \
		../anaconda3/include/qt/QtCore/QDebug \
		../anaconda3/include/qt/QtCore/QStack \
		../anaconda3/include/qt/QtCore/QCache \
		../anaconda3/include/qt/QtCore/QMargins \
		../anaconda3/include/qt/QtCore/qmath.h \
		../anaconda3/include/qt/QtGui/QOpenGLContext \
		../anaconda3/include/qt/QtGui/QOpenGLFramebufferObject \
		../anaconda3/include/qt/QtGui/QOffscreenSurface \
		../anaconda3/include/qt/QtGui/QWindow \
		../anaconda3/include/qt/QtOpenGL/QGLPixelBuffer \
		../anaconda3/include/qt/QtCore/qnumeric.h \
		../anaconda3/include/qt/QtCore/QtNumeric \
		../anaconda3/include/qt/QtWidgets/QWidget \
		../anaconda3/include/qt/QtPrintSupport/QtPrintSupport
	/Users/igorvarga/anaconda3/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

